@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Apr 22 14:22:53 -0500 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim mips_single_cycle_tb_behav -key {Behavioral:sim_1:Functional:mips_single_cycle_tb} -tclbatch mips_single_cycle_tb.tcl -view C:/Users/chase/OneDrive/Documents/Spring23/EECS645/HW09_MIPS_Single_Cycle_Burkdoll/simulation_sources/mips_single_cycle_wave.wcfg -log simulate.log"
call xsim  mips_single_cycle_tb_behav -key {Behavioral:sim_1:Functional:mips_single_cycle_tb} -tclbatch mips_single_cycle_tb.tcl -view C:/Users/chase/OneDrive/Documents/Spring23/EECS645/HW09_MIPS_Single_Cycle_Burkdoll/simulation_sources/mips_single_cycle_wave.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
